version: '3'

services:
   nginx:
      restart: "always"
      image: "docker.io/alfg/nginx-rtmp"
      ports:
         - "8080:80"
         - "1935:1935"
      environment:
         - "RTMP_PORT: 1935"
      volumes:
         - "./nginx/nginx.conf:/etc/nginx/nginx.conf.template"
         - "/var/stream:/var/stream:rw"
   fslc-stream:
      restart: "always" 
      build:
         dockerfile: ./Dockerfile
      env_file: .flaskenv
      ports:
         - "5000:5000"
      volumes:
         - "./export:/fslc_stream/export"
         - "./gunicorn.conf.py:/etc/gunicorn.conf.py"
