FROM docker.io/python:3.12-slim

COPY ./requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

WORKDIR /fslc_stream

EXPOSE 5000

CMD ["/usr/local/bin/python3", "-m", "flask", "-A", "fslc_stream.fslc_stream:create_app()", "run", "-h", "0.0.0.0", "-p", "5000", "--debug"]
